# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tianyaTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'YYKit', '~> 1.0.9'
pod 'SDWebImage', '4.4.2'
pod 'GPUImage'
pod 'AFNetworking', '~> 3.2.1'
pod 'ZFPlayer', '~> 3.2.1'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
pod 'CocoaAsyncSocket', '~> 7.6.3'
pod 'XHLaunchAd', '~> 3.9.8'

  # Pods for tianyaTest

end
